name:  DEV build and deploy
on:
  push:
    branches:
      - main

jobs:
  code-scan:
    name: Build app on Ubuntu
    uses: ./.github/workflows/codeql.yml
  build:
    needs: code-scan
    steps:
      - run: echo "${{ env.ENV_CONFIG }} Branch - Job triggered by a ${{ github.event_name }} event"



