name:  DEV build and deploy
on:
  push:
    branches:
      - main

jobs:
  on-success:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/codeql-analysis.yml@main
        with:
          username: "semere"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

