name:  DEV build and deploy
on:
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "${{ env.ENV_CONFIG }} Branch - Job triggered by a ${{ github.event_name }} event"
      - uses: ./.github/workflows/codeql-analysis.yml
        with:
          username: "semere"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

